//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharaSparksvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class charasparkEntities : DbContext
    {
        public charasparkEntities()
            : base("name=charasparkEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<donation_status> donation_status { get; set; }
        public virtual DbSet<error_log> error_log { get; set; }
        public virtual DbSet<user_type> user_type { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<wish_status> wish_status { get; set; }
        public virtual DbSet<wish> wishes { get; set; }
    }
}
