//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharaSparksvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class error_log
    {
        public int error_id { get; set; }
        public string error_desc { get; set; }
        public System.DateTime error_date { get; set; }
    }
}
