//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharaSparksvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_type
    {
        public user_type()
        {
            this.users = new HashSet<user>();
        }
    
        public int user_type_id { get; set; }
        public string user_type_desc { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
